### ISSUE TITLE
needs examples / more informative errors ?

### ISSUE THREAD

**Issue by simonmichael** [prikhi/hledger-stockquotes#9]
Hi @prikhi, thanks for this nice command. I'd like to list it with the other third-party addons (iadd, interest) and have hledger-install.sh install it. To make it more user ready, I'll file a few wishlist issues here if that's ok ?

Some examples, as complete and reproducible as possible, will be a big help for users getting started. I had some trouble getting it to work when run as `hledger stockquotes`; `hledger-stockquotes` is working better. My biggest question at the moment is which commodities can be fetched. Could you explain the failures below - unsupported commodities, wrong symbols, rate limit exceeded, flaky api, or... ?

```
~/src/hledger$ cat commodities.journal 
commodity USD 0.00
commodity EUR 0.00
commodity GBP 0.00

commodity AAPL 0.00
commodity TSLA 0.00

commodity ADA 0.000000
commodity BTC 0.00000000
commodity ETH 0.000000
~/src/hledger$ hledger-stockquotes -f commodities.journal -n
Error Fetching Symbol `ADA`: JsonHttpException "Error in $: key \"Time Series (Daily)\" not found"
Error Fetching Symbol `BTC`: JsonHttpException "Error in $: key \"Time Series (Daily)\" not found"
Error Fetching Symbol `EUR`: JsonHttpException "Error in $: key \"Time Series (Daily)\" not found"
Error Fetching Symbol `GBP`: JsonHttpException "Error in $: key \"Time Series (Daily)\" not found"
Error Fetching Symbol `TSLA`: JsonHttpException "Error in $: key \"Time Series (Daily)\" not found"
```

I tried it again respecting the rate limit (pretty slow!). This time it fetched TSLA:
```
~/src/hledger$ hledger-stockquotes -f commodities.journal 
Error Fetching Symbol `GBP`: JsonHttpException "Error in $: key \"Time Series (Daily)\" not found"
Waiting 60 seconds to respect API rate limits.
Error Fetching Symbol `ADA`: JsonHttpException "Error in $: key \"Time Series (Daily)\" not found"
Error Fetching Symbol `BTC`: JsonHttpException "Error in $: key \"Time Series (Daily)\" not found"
Error Fetching Symbol `EUR`: JsonHttpException "Error in $: key \"Time Series (Daily)\" not found"
```

I commented out all but AAPL and TSLA and saw intermittent failures:
```
~/src/hledger$ hledger-stockquotes -f commodities.journal 
~/src/hledger$ hledger-stockquotes -f commodities.journal 
~/src/hledger$ hledger-stockquotes -f commodities.journal 
Error Fetching Symbol `TSLA`: JsonHttpException "Error in $: key \"Time Series (Daily)\" not found"
~/src/hledger$ hledger-stockquotes -f commodities.journal 
Error Fetching Symbol `AAPL`: JsonHttpException "Error in $: key \"Time Series (Daily)\" not found"
Error Fetching Symbol `TSLA`: JsonHttpException "Error in $: key \"Time Series (Daily)\" not found"
~/src/hledger$ hledger-stockquotes -f commodities.journal 
Error Fetching Symbol `AAPL`: JsonHttpException "Error in $: key \"Time Series (Daily)\" not found"
Error Fetching Symbol `TSLA`: JsonHttpException "Error in $: key \"Time Series (Daily)\" not found"
~/src/hledger$ hledger-stockquotes -f commodities.journal 
Error Fetching Symbol `AAPL`: JsonHttpException "Error in $: key \"Time Series (Daily)\" not found"
Error Fetching Symbol `TSLA`: JsonHttpException "Error in $: key \"Time Series (Daily)\" not found"
~/src/hledger$ hledger-stockquotes -f commodities.journal 
Error Fetching Symbol `AAPL`: JsonHttpException "Error in $: key \"Time Series (Daily)\" not found"
Error Fetching Symbol `TSLA`: JsonHttpException "Error in $: key \"Time Series (Daily)\" not found"
~/src/hledger$ hledger-stockquotes -f commodities.journal 
~/src/hledger$ hledger-stockquotes -f commodities.journal 
```

Is their rate limiting really strict, is yours not entirely effective, or is it not a rate limit issue ? Might there be more error details that could be reported ?

**Comment by prikhi** [comment]
Heya, that sounds awesome! It does need a lot of work, I basically got it to the point where I can use it ~weekly to pull the latest quotes and then stopped touching it lol.

> I had some trouble getting it to work when run as hledger stockquotes; hledger-stockquotes is working better. 

Ah yeah, I exclusively call it directly but can play around w/ using hledger to call it & see what problems might exist.

```
~/src/hledger$ hledger-stockquotes -f commodities.journal -n
Error Fetching Symbol `ADA`: JsonHttpException "Error in $: key \"Time Series (Daily)\" not found"
Error Fetching Symbol `BTC`: JsonHttpException "Error in $: key \"Time Series (Daily)\" not found"
Error Fetching Symbol `EUR`: JsonHttpException "Error in $: key \"Time Series (Daily)\" not found"
Error Fetching Symbol `GBP`: JsonHttpException "Error in $: key \"Time Series (Daily)\" not found"
Error Fetching Symbol `TSLA`: JsonHttpException "Error in $: key \"Time Series (Daily)\" not found"
```

It uses a part [Alphavantage API](https://www.alphavantage.co/documentation/) which only supports U.S. stocks/funds, so I have to use the excluded currency arg to disable the `AUTO` currency that's created with the `D` directive(which is bad because there is an `AUTO` stock) & a private 401K: `hledger-stockquotes AUTO TA_VFFVX`

```
I tried it again respecting the rate limit (pretty slow!). This time it fetched TSLA:
~/src/hledger$ hledger-stockquotes -f commodities.journal 
Error Fetching Symbol `GBP`: JsonHttpException "Error in $: key \"Time Series (Daily)\" not found"
Waiting 60 seconds to respect API rate limits.
Error Fetching Symbol `ADA`: JsonHttpException "Error in $: key \"Time Series (Daily)\" not found"
Error Fetching Symbol `BTC`: JsonHttpException "Error in $: key \"Time Series (Daily)\" not found"
Error Fetching Symbol `EUR`: JsonHttpException "Error in $: key \"Time Series (Daily)\" not found"
```

Yes it's very slow if you don't limit the currencies, the free API key only allows 5 hits per minute so I make 5 requests, wait 60s, and repeat until all are processed. I've definitely seen requests fail when running the command back to back so I think they're limiting is pretty strict.

When I developed this, they only supported U.S. stocks, but it seems like they've added support for FOREX & Cryptocurrencies so I can look into expanding the API requests.

I naively just parse the journal, grab all the currencies, & remove the excluded ones. Instead, I could have various flags for specifying which currencies should be pulled, e.g., `--equities VTSAX --crypto BTC --forex GBP` w/ maybe even something like `--target EUR`.

I can also re-work the JSON parser to get some better error messages going.

So, a task list would be something like this?

* [x] Improve documentation, add examples
* [x] Test/fix running w/ `hledger stockquotes`
* [ ] Support the FOREX API route
* [x] Support the Crypto API route
* [ ] Re-jigger flags to make currencies explicit? (maybe do the config file issue as well to simplify things?)
* [ ] Allow any target currency?
* [x] Better error messages for API failures

Any additional feedback is welcome!

**Comment by simonmichael** [comment]
Any of these enhancements would be great. I'd love to have a robust tool to fetch prices for most commodities. 

I wondered how it would be to handle args like:

hledger-stockquotes [ COMM ... | not:COMM ... ]

where no args means all the commodities in the journal (except AUTO, for now); negative args (beginning with not:) excludes those commodities; positive args selects only those commodities; and a mix of positives and negatives is an error. 

Other needs: 

Some way to alias commodity symbols, since we don't all use the standard ticker symbols. 

A big one: the ability to fetch prices in another commodity, since of course hledger is international. I don't know if Alphavantage can do that.

**Comment by prikhi** [comment]
I threw a bunch more docs in the README & expanded the output of the `--help` flag. Going to look into better error messages when we hit the API.

Then I'll cut a new release before moving on to other tasks.

**Comment by prikhi** [comment]
Also, do you remember what issues you had when running with `hledger stockqutoes` instead of `hledger-stockquotes`? Seems to work fine w/ how I call it.

**Comment by prikhi** [comment]
When api returns an error, we just print it out:
```
Error Fetching Prices for Symbol `ACCNX`:
	Thank you for using Alpha Vantage! Our standard API call frequency is 5 calls per minute and 500 calls per day. Please visit https://www.alphavantage.co/premium/ if you would like to target a higher API call frequency.
```

When every commodity hits an error, we don't overwrite the prices file & print the following:
```
Error: No price directives were able to be fetched.
```

Updated code to print errors to `stderr` instead of `stdout`.

If this all seems reasonable & `hledger stockquotes -- -a <api-key> ` works fine, I'd like to close this(I made issues for the other features).

**Comment by simonmichael** [comment]
The changes seem great, thanks! Closing.
